### ISSUE TITLE
No ipmi-server, failed to connect to ipmi target server.

### ISSUE THREAD

**Issue by deltamelter** [ateodorescu/home-assistant-ipmi#18]
I have a Dell poweredge server that I control with impitool, but this integration fails to reach it
As I have no ipmi-server addon (because I run hass in docker) I am expecting this to fall back to python lib but if it does, what is it trying to use?  eg, my dell absolutely needs "lanplus" to be specified, the port is default but have tried that and also works.
Example commandline:
```
# ipmitool -I lanplus -H 192.168.1.182 -p 623 -U root -P calvin power status

Chassis Power is on
```

root/calvin is the default ipmi user/pw on Dells 

![image](https://github.com/ateodorescu/home-assistant-ipmi/assets/27061628/dcd5215a-c1cf-466b-8db7-e8bde9a5bd2a)

**Comment by mywp** [comment]
-I lanplus is IPMI V2.0

**Comment by ateodorescu** [comment]
> I have a Dell poweredge server that I control with impitool, but this integration fails to reach it As I have no ipmi-server addon (because I run hass in docker) I am expecting this to fall back to python lib but if it does, what is it trying to use? eg, my dell absolutely needs "lanplus" to be specified, the port is default but have tried that and also works. Example commandline:
> 
> ```
> # ipmitool -I lanplus -H 192.168.1.182 -p 623 -U root -P calvin power status
> 
> Chassis Power is on
> ```
> 
> root/calvin is the default ipmi user/pw on Dells
> 
> ![image](https://user-images.githubusercontent.com/27061628/273187162-dcd5215a-c1cf-466b-8db7-e8bde9a5bd2a.png)

If you don't use the addon and you want to rely on the python library then I can't help you. I don't know what that library does and how it connects to servers. For some servers it works and for others it doesn't. That's why I have implemented the addon. 
Since you run hass in docker then maybe you should give this a go: https://github.com/ateodorescu/home-assistant-addons/issues/3

**Comment by mywp** [comment]
how to install ipmi-server in the version of python ?
like:
raspberry-pi
python -m pip install homeassistant

**Comment by deltamelter** [comment]
> Since you run hass in docker then maybe you should give this a go: [ateodorescu/home-assistant-addons#3](https://github.com/ateodorescu/home-assistant-addons/issues/3)

lol, I did, that was from me too... :grin: Sorry, I forgot that I had opened this.
So yes, to make this work for my dells on a docker based HA, I just built the "add-on" as a docker and tried running as a container.  This usually doesn't work because addons (which are just dockers) have a bunch of required stuff like supervisor and other stuff and this usually stops it running as a standalone docker.   In the case, it runs fine ( it still complains about the supervisor and stuff at startup but still runs.
Please consider the issue closed.
