### ISSUE TITLE
Sensors become unavailable with error "Timeout fetching IPMI resource status data"

### ISSUE THREAD

**Issue by 35gh** [ateodorescu/home-assistant-ipmi#2]
It seems that all sensors are becoming unavailable roughly every 2 minutes for 10 seconds.
Example:
<img width="1628" alt="Capture d’écran 2023-06-21 à 13 02 05" src="https://github.com/ateodorescu/home-assistant-ipmi/assets/90415090/08290477-c233-4641-8592-716f28bd60c5">

**Comment by ateodorescu** [comment]
Sensor values are fetched every 10 seconds or the value configured for the server (check the `configure` button).
![Screenshot 2023-06-21 at 14 10 46](https://github.com/ateodorescu/home-assistant-ipmi/assets/1575894/cdb9ef52-4aab-4984-a1d3-52c2c5008b23)

Not sure why you see that gap.

**Comment by 35gh** [comment]
I see this error in the logs:
```
 Logger: custom_components.ipmi
Source: helpers/update_coordinator.py:229
Integration: IPMI connector (documentation)
First occurred: 12:56:16 (11 occurrences)
Last logged: 13:22:06
Timeout fetching IPMI resource status data
```

**Comment by 35gh** [comment]
I've increased async_timeout value in __init__.py from 10 to 20 and it has drastically reduced the timeouts.
Line 84, from:
`async with async_timeout.timeout(10):`
to:
`async with async_timeout.timeout(20):`

I got one timeout during the night, I have further increased the value to 25.

**Comment by 35gh** [comment]
Even with 25 or 30, I'm still getting some timeouts from time to time. It may be useful to implement a logic that  if a timeout occurs, previous values are used until next retry.

**Comment by ateodorescu** [comment]
fixed in https://github.com/ateodorescu/home-assistant-ipmi/releases/tag/v1.1.1

**Comment by ateodorescu** [comment]
https://github.com/ateodorescu/home-assistant-ipmi/releases/tag/v1.1.1
