### ISSUE TITLE
Sensors no longer available after update to 2024.3

### ISSUE THREAD

**Issue by 35gh** [ateodorescu/home-assistant-ipmi#29]
Sensors are no longer available after update to 2024.3. On/off switch seems to be available.

I see the following error in logs:
`Exception in async_new_sensors when dispatching 'ipmi_new_sensor_signal.279973283e5512c52af8e8f2f97d15da': (['cpu_temp', 'system_temp', 'peripheral_temp', 'mb_10g_temp', 'dimma1_temp', 'dimma2_temp', 'dimmb1_temp', 'dimmb2_temp', 'vccp', 'vdimm', '12v', '5vcc', '33vcc', 'vbat', '5v_dual', '33v_aux', 'fan1', 'fan2', 'fan3', 'fan4', 'instantaneous_power_reading', 'minimum_during_sampling_period', 'maximum_during_sampling_period', 'average_power_reading_over_sample_period', 'sampling_period'],) Traceback (most recent call last): File "/config/custom_components/ipmi/sensor.py", line 213, in async_new_sensors _async_add_entities(hass, registry, async_add_entities, server_id, new_entities) File "/config/custom_components/ipmi/sensor.py", line 224, in _async_add_entities ipmiserver = get_ipmi_server(hass, server_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/ipmi/helpers.py", line 24, in get_ipmi_server return get_ipmi_data(hass)[SERVERS][server_id] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^ KeyError: '279973283e5512c52af8e8f2f97d15da' `

Thank you!

**Comment by SteffenM-DE** [comment]
Me too. Only state sensor is working after update to 2024.03.

**Comment by ChriZathens** [comment]
Me three...

**Comment by ateodorescu** [comment]
It happened to me as well after the last update. I looked into this but I can't figure it out.
Do you also see this error in your logs? ![Screenshot 2024-03-07 at 13 39 26](https://github.com/ateodorescu/home-assistant-ipmi/assets/1575894/62dd20e9-a42b-4c96-bf32-178b13a0e13f)

**Comment by 35gh** [comment]
@ateodorescu yes I see this error as well.

**Comment by ateodorescu** [comment]
I think this error is related to this issue. I'll see if I have more time to look into this during the weekend.

**Comment by tikismoke** [comment]
In my case update done those logs:

```
2024-03-07 21:17:43.678 ERROR (SyncWorker_36) [homeassistant.util.logging] Exception in async_new_sensors when dispatching 'ipmi_new_sensor_signal.89601f0bb75ee13a17d31347fdeffde3': (['inlet_temp', 'exhaust_temp', 'temp', 'vcore_pg', '33v_pg', '5v_aux_pg', 'm23_vpp_pg', '105v_pg', 'bp0_5v_pg', 'm23_vddq_pg', 'm23_vtt_pg', '5v_switch_pg', 'vccio_pg', '25v_aux_pg', 'm01_vddq_pg', 'm01_vtt_pg', 'ndc_pg', 'm01_vpp_pg', '15v_pg', 'ps2_pg_fail', 'ps1_pg_fail', 'bp1_5v_pg', 'bp2_5v_pg', '15v_aux_pg', 'voltage_1', 'voltage_2', 'pfault_fail_safe', 'dimm_pg', 'fivr_pg', 'fan1', 'fan2', 'fan3', 'fan4', 'fan5', 'fan6', 'fan_redundancy', 'instantaneous_power_reading', 'minimum_during_sampling_period', 'maximum_during_sampling_period', 'average_power_reading_over_sample_period', 'sampling_period'],)
Traceback (most recent call last):
  File "/config/custom_components/ipmi/sensor.py", line 213, in async_new_sensors
    _async_add_entities(hass, registry, async_add_entities, server_id, new_entities)
  File "/config/custom_components/ipmi/sensor.py", line 224, in _async_add_entities
    ipmiserver = get_ipmi_server(hass, server_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipmi/helpers.py", line 24, in get_ipmi_server
    return get_ipmi_data(hass)[SERVERS][server_id]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '89601f0bb75ee13a17d31347fdeffde3'

```

**Comment by alx-k** [comment]
Just to add to this since it wasn't mentioned before, I also get this error at the sime time as the "no running event loop" error:

`Logger: py.warnings`
`Quelle: components/recorder/util.py:232`
`Erstmals aufgetreten: 10:00:10 (1 Vorkommnisse)`
`Zuletzt protokolliert: 10:00:10`

`/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/result.py:551: RuntimeWarning: coroutine 'EntityPlatform._async_add_entity' was never awaited made_rows = [make_row(row) for row in rows]`

**Comment by dodo-dk** [comment]
A Downgrade to Version 1.1.4 (IPMI connector) works for me.
All Versions since 1.2.0 don´t work with 2024.3.

I hope that helps to find the problem.

**Comment by Yunlliang** [comment]
> 降级到版本 1.1.4（IPMI 连接器）对我有用。 自 1.2.0 以来的所有版本均不适用于 2024.3。
> 
> 我希望这有助于找到问题。

It works for me, too

**Comment by indiantechsupporter** [comment]
Downgrade worked fine for me too. 👍🏼

**Comment by BigWebstas** [comment]
Downgrade to 1.1.4 fixed my issue as well

**Comment by ateodorescu** [comment]
I just released a new version which fixes the problem. Please report back that it's working for you as well.
Thanks!

**Comment by 35gh** [comment]
1.4.0 works for me: sensors are available and no error in logs. Thank you!

**Comment by molekylspektroskopi** [comment]
Works perfectly here with 1.4.0

**Comment by dodo-dk** [comment]
Thanks, with 1.4.0 all ok

**Comment by kellcomnet2** [comment]
Another confirmation, that 1.4 resolved the issue, thank you for the fast fix on this.
