### ISSUE TITLE
IPMI integration is slow to start since IPMI server update to v1.2.9

### ISSUE THREAD

**Issue by 35gh** [ateodorescu/home-assistant-ipmi#32]
IPMI server prompted for an update this morning (from v1.2.7 to v1.2.9) and since then the IPMI integration is slow to start, and even failing from time to time.

I see the following warnings in logs:

```
Enregistreur: homeassistant.components.switch
Source: runner.py:188
intégration: Commutateur (documentation, problèmes)
S'est produit pour la première fois: 10:17:25 (1 occurrences)
Dernier enregistrement: 10:17:25
Setup of switch platform ipmi is taking over 10 seconds.
```

```
Enregistreur: homeassistant.bootstrap
Source: bootstrap.py:601
S'est produit pour la première fois: 10:17:35 (1 occurrences)
Dernier enregistrement: 10:17:35
Waiting on integrations to complete setup: ipmi, ipmi.switch
```

Thanks!

**Comment by ateodorescu** [comment]
Nothing changed except for the version number: https://github.com/ateodorescu/home-assistant-addons/compare/v1.2.7...main
I did some tests with a user, trying to figure out if we can setup a fixed version number for impitool inside the docker container (that was 1.2.8) but then I reverted back the changes. So, 1.2.9 is the same as 1.2.7.
