### ISSUE TITLE
Integration stopped working after update to HA 2024.4.0

### ISSUE THREAD

**Issue by 35gh** [ateodorescu/home-assistant-ipmi#34]
Hi,

After update to HA 2024.4.0, all integration entities but state became unavailable.

I see those suspicious errors in logs, not sure they are related:
```
Enregistreur: homeassistant
Source: util/async_.py:35
S'est produit pour la première fois: 23:34:13 (1 occurrences)
Dernier enregistrement: 23:34:13
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 629, in async_add_entities
    await add_func(coros, entities, timeout)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 535, in _async_add_and_update_entities
    tasks = [create_eager_task(coro) for coro in coros]
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 35, in create_eager_task
    loop=loop or get_running_loop(),
                 ^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

```

```
Enregistreur: py.warnings
Source: runner.py:189
S'est produit pour la première fois: 23:34:13 (1 occurrences)
Dernier enregistrement: 23:34:13

/usr/local/lib/python3.12/threading.py:299: RuntimeWarning: coroutine 'EntityPlatform._async_add_entity' was never awaited def __enter__(self):
```

Thanks!

**Comment by corgan2222** [comment]
I can confirm this bug after updating to 2024.0.

Debug output:
![grafik](https://github.com/ateodorescu/home-assistant-ipmi/assets/12233951/faae4c21-7f44-4cd6-b017-6d597e65fabd)


This happens to both of my servers (dell and ASRock). It looks, that only the SDR List Items are effected.
The power state and the power switch are available.

![grafik](https://github.com/ateodorescu/home-assistant-ipmi/assets/12233951/8ff03644-681f-4bcc-9cf1-bf7470741e34)

**Comment by 35gh** [comment]
1.6.0 brought back the sensors for me, thank you. Hope you'll sort out how to play with those bloody APIs :)
