### ISSUE TITLE
Feature request: add integration to HACS

### ISSUE THREAD

**Issue by 35gh** [ateodorescu/home-assistant-ipmi#4]
It will be good if this integration can be added to HACS (Home Assistant Community Store):
https://hacs.xyz/docs/publish/start

This will simplify installation and updates, thank you!

**Comment by jpmiller25** [comment]
Second this! You'll also increase your reach greatly, I initially searched HACS for ipmi and found nothing before I found your script here. Thanks!

**Comment by ateodorescu** [comment]
Does HACS support addons? I don't see anything related to addons on that page.

**Comment by ateodorescu** [comment]
I'll have a look at HACS to add this integration there.
On the other hand I wanted to include the other integration that I have done too but that one requires an addon to do the job: https://github.com/ateodorescu/home-assistant-ipmitool

What do you think would be the proper way to do for the `ipmitool` integration? Should I add it to HACS too and just let the users know that it needs an addon to run or just leave it out?

**Comment by 35gh** [comment]
I would suggest to merge both integration in one made available in HACS.

Users can be instructed on how to install the add-on during the integration installation flow.

The integration can then detect if the ipmitool add-on is available, and offer the possibility to the user to select it in the configuration screen or fall back to rmcp if not.

**Comment by ateodorescu** [comment]
So, there's only one integration now that knows how to use the addon if available, otherwise it falls back to the python library. I'm waiting for the brands PR to be merged (https://github.com/home-assistant/brands/pull/4512) and then the actions for HACS to run successfuly (https://github.com/ateodorescu/home-assistant-ipmi/actions).
I guess that's all I have to do so that the integration goes into HACS.

**Comment by ateodorescu** [comment]
Waiting for PR to be merged in HACS: https://github.com/hacs/default/pull/1962

**Comment by 35gh** [comment]
Thanks! In the meantime I've manually installed the integration using custom depot in HACS and it works fine.

**Comment by ateodorescu** [comment]
@35gh how does the PR merge work? I saw that you reviewed the PR. Who can do that? Are you part of the HACS team or simply anyone interested could review a PR?

**Comment by joggs** [comment]
I think we have to wait. When I published mine, there were frustrating weeks while waiting for the 3 required approvers to make time reviewing it and approving it. There seems to be alot of PR's waiting

**Comment by ateodorescu** [comment]
The PR has been merged to HACS.

**Comment by ateodorescu** [comment]
Finally the PR was merged and the integration is available in `HACS`.
