### ISSUE TITLE
Dual CPU server only shows 1 CPU temperature

### ISSUE THREAD

**Issue by kimfr** [ateodorescu/home-assistant-ipmi#40]
I have a Dell R720 dual CPU and with the latest IPMI it is still only showing one temperature.

I suspect the issue might be that the sdr elist shows them having the same name:
Temp             | 0Eh | ok  |  3.1 | 45 degrees C
Temp             | 0Fh | ok  |  3.2 | 42 degrees C

I have confirmed that these are the correct values for CPU1 and CPU2.

**Comment by LucidityCrash** [comment]
I made a quick and nasty PR
https://github.com/ateodorescu/home-assistant-addons/pull/15

**Comment by ateodorescu** [comment]
> I made a quick and nasty PR [ateodorescu/home-assistant-addons#15](https://github.com/ateodorescu/home-assistant-addons/pull/15)

That PR is too nasty to merge it in :)
Please make it generic to work with more CPUs as well.
Thanks!

**Comment by LucidityCrash** [comment]
Is using "elist" instead of "list" a reasonable option ?  I know it works
on my Dell but how universal is it ? ... that way there is a device ID we
can use in the structure ... it could replace the current ID you use which
is just a lower cased and sanitised version of the description ?  The name
of the sensor could then be the Description plus the ID ... should be
completely unique that way.

Downsides is this is a breaking change as existing sensors would have their
names changed, and every sensor would have the ID in their name which some
might say isn't pretty.

**Comment by ateodorescu** [comment]
I agree that using `elist` would have been better.
I'm not sure how long it takes on some Dells to fetch that list. I think I tried using `elist` once but there was one user that had a very slooooow Dell and the user was receiving a timeout in Hass until the response came back from the server.
I think that for keeping compatibility with existing installations we can include a number for such sensors. I believe that the order the sensors are listed in is always the same. Would you agree?

**Comment by LucidityCrash** [comment]
PR updated ... its not that much better but it "should" now manage any multiple of things, where things is any sensor.

**Comment by LucidityCrash** [comment]
PR was merged and I've updated my addon so I'm using the original one instead and can confirm I can see 2 CPU's:
![image](https://github.com/user-attachments/assets/0f1f9f5f-cf11-4a61-9037-b6cda13bf6f6)

Any one got something with more CPU's to see if it holds up ?

**Comment by kimfr** [comment]
I have a R720 dual core so I can test.

I've got a HAOS test setup - currently running 
Core 2024.11.2
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241106.2
IPMI Server 1.7.0

I'm happy to test - just not sure how to go about that.

**Comment by ateodorescu** [comment]
> I have a R720 dual core so I can test.
> 
> I've got a HAOS test setup - currently running Core 2024.11.2 Supervisor 2024.11.4 Operating System 13.2 Frontend 20241106.2 IPMI Server 1.7.0
> 
> I'm happy to test - just not sure how to go about that.

you need to install the latest version of https://github.com/ateodorescu/home-assistant-addons

**Comment by kimfr** [comment]
Initially wasn't working but after doing a Rebuild via the Add-On page for IPMItool server - I now have 2 CPU Temp's.

Thanks
