### ISSUE TITLE
Dell R720XD connect error

### ISSUE THREAD

**Issue by ChenSV-github** [ateodorescu/home-assistant-ipmi#53]
Unable connect to ipmi whatever i change,using ipmitool lanplus testing connection is ok (not inside hass)
HASS is installed at windows server os in hyper-v

**Comment by ateodorescu** [comment]
@ChenSV-github You should install this addon https://github.com/ateodorescu/home-assistant-addons/tree/main/ipmi-server
Without the addon the integration won't work.
