### ISSUE TITLE
Power sensors on Supermicro server

### ISSUE THREAD

**Issue by massimilianopal** [ateodorescu/home-assistant-ipmi#54]
Hello, 
I would like to read the power sensors on a Supermicro  X9DR7-TF+. Is it possible? Thanks

**Comment by kimfr** [comment]
Hello,

I use the plug-in myself for some Dell and HP servers. My understanding is that whatever is returned with the below command is what you should see in Home Assistant:
`ipmitool -I lanplus -H <ip> -U <user> -P <password> sdr elist full`

**Comment by ateodorescu** [comment]
> Hello, I would like to read the power sensors on a Supermicro X9DR7-TF+. Is it possible? Thanks

Did you install the addon?

**Comment by massimilianopal** [comment]
Yes I see this entities:

Power on/Soft shutdown
Server +3.3VSB
Server +5VSB
Server 10G Temp
Server 12V
Server 3.3V
Server 5V
Server CPU1 Temp
Server CPU1 Vcore
Server CPU2 Temp
Server CPU2 Vcore
Server FAN1
Server FAN2
Server FAN3
Server FAN4
Server FAN5
Server FAN6
Server FANA
Server FANB
Server FANC
Server P1-DIMMA1 TEMP
Server P1-DIMMB1 TEMP
Server P1-DIMMC1 TEMP
Server P1-DIMMD1 TEMP
Server P2-DIMME1 TEMP
Server P2-DIMMF1 TEMP
Server P2-DIMMG1 TEMP
Server P2-DIMMH1 TEMP
Server PCH Temp
Server Peripheral Temp
Server State
Server System Temp
Server VBAT
Server VDIMM AB
Server VDIMM CD
Server VDIMM EF
Server VDIMM GH
Server VTT

But I don't see the power entities

**Comment by massimilianopal** [comment]
No. After installing it it's perfect. Thanks
