### ISSUE TITLE
problem configuring

### ISSUE THREAD

**Issue by neo2angel** [ateodorescu/home-assistant-ipmi#7]
Hello

I am trying to configure the addon, but I don't know what value to put in the "port" field, I have a gibabyte igabyte wrx80 su8 ipmi board and I am very lost, I would appreciate a little help, because at first it connects, but later it does not detect neither devices nor sensors.

thank you so much

**Comment by ateodorescu** [comment]
@neo2angel If you did not change the port number in your ipmi server configuration then you don't have to change the default port in the addon configuration.
Do you get any errors when using `ipmitool` to connect to your server?

**Comment by ateodorescu** [comment]
In the ipmi integration use the `configure` button on your device to change the `scan interval`. Try to increase it.

I'm not sure why this happens with your server.

**Comment by neo2angel** [comment]
increase it? I had reduced, I will try to see

**Comment by neo2angel** [comment]
nothing, still not working

**Comment by ateodorescu** [comment]
> nothing, still not working

Ok, let's try the following:

1. What happens if you use `ipmitool` directly? Can it connect to your server? Does it work? Can you call it frequently without errors?
2. In the addon configuration change `log_level` to `debug` and let's see what the `Log` tab reports.

**Comment by chunkster29** [comment]
what do put in the fields i've got a dell poweredge on the default ip '192.168.1.120' user 'root' pass 'somepassword on standard port homeassistant is running on different server

**Comment by neo2angel** [comment]
Sorry for not responding sooner, I was out on vacation.

where do i register? I don't know where to touch

when i do it through the browser it works fine

**Comment by neo2angel** [comment]
I think I already managed to change it to debug.log, I get this:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: IPMItool server
 IPMItool server
-----------------------------------------------------------
 Add-on version: 1.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.8.4
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
[13:02:12] INFO: Starting PHP-FPM...
s6-rc: info: service legacy-services successfully started
[13:02:13] INFO: Starting NGinx...

**Comment by ateodorescu** [comment]
@neo2angel I have changed the addon to log errors. Please install the addon with the latest code and let's see what the log says.

**Comment by ateodorescu** [comment]
The last versions of ipmi integration and addon should have this fixed.
