### ISSUE TITLE
Unknown error connecting

### ISSUE THREAD

**Issue by dekesone** [ateodorescu/home-assistant-ipmi#8]
Multiple attempts to configure the connector, and I receive the error pasted below.  I am able to access IPMI from both the web interface and the IPMIView20 software.
Any suggestions on how to troubleshoot this issue?

This error originated from a custom integration.

Logger: custom_components.ipmi
Source: custom_components/ipmi/__init__.py:355
Integration: IPMI connector (documentation, issues)
First occurred: August 21, 2023 at 10:22:42 PM (9 occurrences)
Last logged: 12:34:34 PM

Error connecting to IPMI server 192.168.1.121: CompletionCodeError cc=0x81 desc=Unknown error description

**Comment by ateodorescu** [comment]
The python library that this integration uses fails with some servers. If you can install this [addon](https://github.com/ateodorescu/home-assistant-addons/tree/main/ipmi-server) then you might have better chances. The addon uses `ipmitool` to connect to your server.

**Comment by xBelladonna** [comment]
Is it possible to install the extension if using the Home Assistant container on its own? I'm using docker compose to host my instance in a container but the addon looks to be for Home Assistant OS.

**Comment by ateodorescu** [comment]
@xBelladonna Someone managed to install the addon in docker: https://github.com/ateodorescu/home-assistant-addons/issues/3

**Comment by MNeverOff** [comment]
@xBelladonna I took a minute and created the docker container + pushed it to Docker Hub. Feel free to use `mneveroff/ipmi-server:1.0.0` or `:latest`.
See details: https://github.com/MNeverOff/ipmi-server
