### ISSUE TITLE
Finished fetching IPMI resource status data in 10.002 seconds (success: False)

### ISSUE THREAD

**Issue by chunkster29** [ateodorescu/home-assistant-ipmi#9]
I've tryied setting it up but it won't connect can connect via the command line using  ipmitool -I lanplus -H 192.168.1.125 -U root -P XXXXXXXX sdr elist all does the addon support lanplus as a connection method

**Comment by ateodorescu** [comment]
`lanplus` is supported. In fact it's the first connection type that the server tries. Maybe I'll improve this to be able to spit the error in the log.

**Comment by chunkster29** [comment]
following up this what is being shown on the webserver {"success":false,"message":"Wrong connection data provided!"}

**Comment by ateodorescu** [comment]
Please try to open the following url in your browser:
`http://YOUR_HASS_IP:9595/?host=YOUR_SERVER_IP&port=623&user=YOUR_USER&password=YOUR_PASSWORD` and let's see what it returns.
`YOUR_HASS_IP` is the IP address of your home assistant server.
`YOUR_SERVER_IP` is the IP address of the IPMI server.

**Comment by chunkster29** [comment]
now that's returning json data

**Comment by ateodorescu** [comment]
That's exactly what the integration does when using the addon.

**Comment by chunkster29** [comment]
well looks like the connect information isn't getting passed for some reason

**Comment by ateodorescu** [comment]
Might be related to https://github.com/ateodorescu/home-assistant-ipmi/issues/10

**Comment by chunkster29** [comment]
that as fixed the problem

**Comment by ateodorescu** [comment]
fixed in https://github.com/ateodorescu/home-assistant-ipmi/releases/tag/v1.1.1
